/**
 * @type {import('@docusaurus/plugin-content-docs/lib/sidebars/types').Sidebars}
 */
module.exports = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the root of the docs directory
    },
  ],
};

